# Generated by Django 3.2.3 on 2021-06-22 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_types', models.CharField(choices=[('regular', 'Regular'), ('square', 'Square')], default='regular', max_length=12)),
                ('pizza_sizes', models.CharField(choices=[('extra small', 'Extra Small'), ('small', 'Small'), ('medium', 'Medium'), ('medium large', 'Large'), ('large', 'Large'), ('extra large', 'Extra Large')], default='medium', max_length=15)),
                ('pizza_toppings', models.CharField(choices=[('onion', 'Onion'), ('tomato', 'Tomato'), ('corn', 'Corn'), ('cheese', 'Cheese'), ('capsicum', 'Capsicum'), ('jalapeno', 'Jalapeno')], default='cheese', max_length=12)),
            ],
        ),
    ]
